### ISSUE TITLE
3.8 update

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [robby-u/tellipatch#1]
It's not really an issue per se, but when's the new tellipatch (with v3.8) coming out???

**Comment by vec702** [comment]
cURL requests all repositories latest releases, so the first phase should already be patching to v3.8.
It still displaying v3.7b is a typo on the author's part.

**Comment by vec702** [comment]
there was a hotfix that may or may not have fixed this typo. for more information, [read here](https://github.com/Tellilum/.hack-fragment-Definitive-Translation/releases/tag/v3.8_Hotfix).
